export const DIMINISHING_FIXED_EQUAL_AMORTIZATION = 'DIMINISHING_FIXED_EQUAL_AMORTIZATION';
export const STRAIGHT_LINE_AMORTIZATION = 'STRAIGHT_LINE_AMORTIZATION';
export const USER_ADMIN = 'ADMIN';
export const USER_STAFF = 'STAFF';
export const LOAN_APPROVED = 'A';
export const LOAN_DISAPPROVED = 'D';