module.exports = {
    USER_ADMIN  : 'ADMIN',
    USER_STAFF : 'STAFF',
    DIMINISHING_FIXED_EQUAL_AMORTIZATION : 'DIMINISHING_FIXED_EQUAL_AMORTIZATION',
    STRAIGHT_LINE_AMORTIZATION : 'STRAIGHT_LINE_AMORTIZATION'
};